Introduce partial C11 support
eliben/pycparser pull request #429
Opened 2021-08-29 09:52 UTC by vit9696

Implemented _Noreturn, _Static_assert, _Thread_local. Also fixed
tests with preprocessor on macOS.

2021-08-30 13:26 UTC, eliben requested changes

2021-08-30 13:26 UTC, eliben commented on tests/test_c_generator.py
> +            _Noreturn int x(void) {
I'd like to see a standalone test for `_Noreturn` in `test_c_parser`. Just a small code snippet, and a test that verifies that the proper specifier is added to the function declaration.

2021-08-30 13:26 UTC, eliben commented on utils/fake_libc_include/_fake_defines.h
> +#define thread_local _Thread_local
Please add a specific parser test for `_Thread_local` too. The C-to-C tests are insufficient for this - they won't catch errors in building the AST in the parser.

2021-08-30 13:26 UTC, eliben commented on utils/fake_libc_include/_fake_defines.h
> +#define thread_local _Thread_local
... and same comment for `static_assert`. Please test it both inside and outside a function, in `test_c_parser`.

2021-08-30 13:26 UTC, eliben commented on pycparser/c_lexer.py
> +        keyword_map[''.join([keyword[:2].upper(), keyword[2:].lower()])] = keyword
Do you really need the `join` here, or would a `+` do?

2021-08-30 15:23 UTC, vit9696 commented
All done.

2021-08-30 17:26 UTC, vit9696 commented
For your interest, the tests fail due to some GitHub Actions downtime. They pass on macOS for me.

2021-08-31 13:02 UTC, eliben approved these changes
Thanks for your patience in pushing this through. LGTM.
I have some minor styling comments, but will apply them myself after merging this PR - shortly.

2021-08-31 13:05 UTC, merged